name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: |
          dotnet build src/Llamas.Abstractions/Llamas.Abstractions.csproj -c Release
          dotnet build src/Llamas/Llamas.csproj -c Release
          dotnet build src/Llamas.Container/Llamas.Container.csproj -c Release
      - name: Test
        run: dotnet test test/Llamas.Tests.Unit/Llamas.Tests.Unit.csproj
      - name: Pack
        run: |
          dotnet pack src/Llamas.Abstractions/Llamas.Abstractions.csproj --include-source -c Release -o packed --no-build
          dotnet pack src/Llamas/Llamas.csproj --include-source -c Release -o packed --no-build
          dotnet pack src/Llamas.Container/Llamas.Container.csproj --include-source -c Release -o packed --no-build
      - name: Push Packages
        run: dotnet nuget push ./packed/*.nupkg --skip-duplicate --no-symbols --source https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_TOKEN}}
      - name: Push Symbols
        run: dotnet nuget push ./packed/*.snupkg --skip-duplicate --source https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_TOKEN}}   
